# Form implementation generated from reading ui file 'regist.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from widgets.sql import cn,cur
from widgets import sql
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import *
from widgets.signal import Signall

import requests,re
class SignSignal(QObject):
    sign_up_signal=pyqtSignal()
    back_signal=pyqtSignal()
class Ui_regist(QMainWindow):

    def __init__(self) -> None:
        super().__init__()
        self.s_up=SignSignal()
        self.back=SignSignal()
        self.setWindowTitle("Online school")
        # MainWindow = QtWidgets.QMainWindow()
        # ui = Ui_regist()
        # self.setupUic()
        
    def setupUic(self, MainWindow):
        style_input = """
        QLineEdit{
            font-size: 14px;
            font-weight: 250;
            border-radius: 5px;
        }
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 646)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 39, 400, 80))
        self.label.setMinimumSize(QtCore.QSize(400, 80))
        self.label.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(33, 122, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 140, 350, 40))
        self.lineEdit.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet(style_input)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 210, 350, 40))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet(style_input)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 280, 350, 40))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setStyleSheet(style_input)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 350, 350, 40))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setStyleSheet(style_input)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 420, 350, 40))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setStyleSheet(style_input)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 430, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(170, 500, 391, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(43, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.pushButton_2.clicked.connect(self.click_backbtn)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(43, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.check_data)
        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Registration"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "User"))
        self.label_4.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Phone"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
    # def click_regbtn(self):
    #     self.s_up.sign_up_signal.emit()
    #     self.hide()
    def click_backbtn(self):
        self.back.back_signal.emit()
        self.hide()
    def check_data(self):
        if len(self.lineEdit.text())<1:
            self.name_error=QMessageBox.critical(self,"Error!!","Enter must name!!")
        elif len(self.lineEdit_2.text())<1:
            self.sur_error=QMessageBox.critical(self,"Error!!","Enter must username!!")
        elif not re.match(r"[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+", self.lineEdit_3.text()):
            self.emeil_edit_error=QMessageBox.critical(self,"Error","Please enter the correct email address!!!")
        elif len(self.lineEdit_4.text())<12:
            self.phone=QMessageBox.critical(self,"Error!!!","Error phone number !")
        elif len(self.lineEdit_5.text())<8:
            self.pass_err=QMessageBox.critical(self,"Error","password must be at least 8 characters long")
        else:
            name=self.lineEdit.text()
            surname=self.lineEdit_2.text()
            pasword=self.lineEdit_4.text()
            if name:
                if surname:
                    if pasword:
                        cur.execute(sql.date.add_pupl(),(name,surname,pasword))
                        cn.commit()
            self.signedup = QMessageBox.about(self, "Done.", "✅ You are registered succesfully!!!")
            self.s_up.sign_up_signal.emit()
            self.hide()
            print("Finish")
    # def click_regbtn(self):


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_regist()
#     ui.setupUic(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
